name = "route-filter-worker"
main = "src/worker.ts"
compatibility_date = "2023-08-01"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
STORAGE_API_ENDPOINT = "abc123"
