name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      DOTNET_VERSION: 7.0.x
      SITE_PROJECT_NAME: ProgrammerAl.Site
      SLN_PATH: ${{ github.workspace }}/src/ProgrammerAl.Site/ProgrammerAl.Site.sln
      DYNAMIC_CONTENT_UPDATER_PROJECT_PATH: ${{ github.workspace }}/src/ProgrammerAl.Site/DynamicContentUpdater/DynamicContentUpdater.csproj
      SITE_PROJECT_PATH: ${{ github.workspace }}/src/ProgrammerAl.Site/ProgrammerAl.Site/ProgrammerAl.Site.csproj
      SITE_PUBLISH_OUTPUT_PATH: ${{ github.workspace }}/outputs/ProgrammerAl.Site

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: .NET Restore
        run: dotnet restore ${{ env.SLN_PATH }}
      - name: .NET Build
        run: dotnet build ${{ env.SLN_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: .NET Test
        run: dotnet test ${{ env.SLN_PATH }} --no-restore --verbosity normal
      - name: Run Dynamic Content Creator
        run: dotnet run --project ${{ env.DYNAMIC_CONTENT_UPDATER_PROJECT_PATH }} --no-restore --verbosity normal -- --AppRootPath "${{ github.workspace }}/src"
      - name: .NET Publish
        run: dotnet publish ${{ env.SITE_PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --output ${{ env.SITE_PUBLISH_OUTPUT_PATH }}
      - name: Deploy Static Site
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: ${{ env.SITE_PUBLISH_OUTPUT_PATH }}
          skip_app_build: true
          skip_api_build: true



