name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_call:
    secrets:
      arm_client_id:
        required: true
      arm_client_secret:
        required: true
      arm_tenant_id:
        required: true
      arm_subscription_id:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      DOTNET_VERSION: 8.0.x
      SITE_PROJECT_NAME: ProgrammerAl.Site
      SRC_DIRECTORY_PATH: ${{ github.workspace }}/src/
      BUILD_ARTIFACTS_PATH: ${{ github.workspace }}/build_artifacts
      DYNAMIC_CONTENT_UPDATER_PROJECT_PATH: ${{ github.workspace }}/src/ProgrammerAl.Site/DynamicContentUpdater/DynamicContentUpdater.csproj
      PULUMI_PROJECT_FILE_PATH: ${{ github.workspace }}/infra/pulumi-infra-deploy/pulumi-infra-deploy.csproj
      ARM_CLIENT_ID: ${{ secrets.arm_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.arm_client_secret }}
      ARM_TENANT_ID: ${{ secrets.arm_tenant_id }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.arm_subscription_id }}
      DYNAMIC_CONTENT_UPDATER_OUTPUT_PATH: ${{ github.workspace }}/static_content_output
      STORAGE_URL: https://content.programmeral.com
      PULUMI_STACK_NAME: prod

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.3.0
      - name: Npm Install Wrangler
        run: npm install --location=global wrangler
      - name: Install Pulumi
        uses: pulumi/setup-pulumi@v2

        # Run the dynamic content creator first because some stuff it outputs goes to the blazor site
      - name: Run Dynamic Content Creator
        run: dotnet run --project ${{ env.DYNAMIC_CONTENT_UPDATER_PROJECT_PATH }} --no-restore --verbosity normal -- --AppRootPath "${{ env.SRC_DIRECTORY_PATH}}" --OutputDirectory "${{ env.DYNAMIC_CONTENT_UPDATER_OUTPUT_PATH }}" --StorageUrl "${{ env.STORAGE_URL }}"

      - name: Cake Frosting Build
        run: dotnet run --project build/build/Build.csproj -- --configuration=${{ env.CONFIGURATION }} --srcDirectoryPath=${{ env.SRC_DIRECTORY_PATH }} --BuildArtifactsPath=${{ env.BUILD_ARTIFACTS_PATH }}

      - name: Dotnet Restore - Deploy Project
        run: dotnet restore ${{ env.PULUMI_PROJECT_FILE_PATH }}
      - name: Cake Frosting - Deploy
        run: dotnet run --project ${{ github.workspace }}/deploy/deploy/Deploy.csproj -- --configuration=${{ env.CONFIGURATION }} --PulumiStackName=${{ env.PULUMI_STACK_NAME }} --ReleaseVersion=${{ inputs.release_tag_id }} --WorkspacePath=${{ github.workspace }}

      # - name: Deploy Static Site
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      #     action: 'upload'
      #     app_location: ${{ env.SITE_PUBLISH_OUTPUT_PATH }}/wwwroot
      #     output_location: ''          
      #     skip_app_build: true
      #     skip_api_build: true
      # - name: Push Content Files
      #   uses: bacongobbler/azure-blob-storage-upload@main
      #   with:
      #     source_dir: '${{ github.workspace }}/src/ProgrammerAl.Site.Content'
      #     container_name: 'sitecontent'
      #     connection_string: ${{ secrets.PublicBlobStorageConnectionString }}
      #     sync: 'true'  


